!function(e){"function"==typeof define&&define.amd?define(["jquery"],e):e("object"==typeof exports?require("jquery"):jQuery)}(function(e){function n(e){return u.raw?e:encodeURIComponent(e)}function o(e){return u.raw?e:decodeURIComponent(e)}function i(e){return n(u.json?JSON.stringify(e):String(e))}function r(e){0===e.indexOf('"')&&(e=e.slice(1,-1).replace(/\\"/g,'"').replace(/\\\\/g,"\\"));try{return e=decodeURIComponent(e.replace(c," ")),u.json?JSON.parse(e):e}catch(n){}}function t(n,o){var i=u.raw?n:r(n);return e.isFunction(o)?o(i):i}var c=/\+/g,u=e.cookie=function(r,c,a){if(arguments.length>1&&!e.isFunction(c)){if(a=e.extend({},u.defaults,a),"number"==typeof a.expires){var f=a.expires,s=a.expires=new Date;s.setTime(+s+864e5*f)}return document.cookie=[n(r),"=",i(c),a.expires?"; expires="+a.expires.toUTCString():"",a.path?"; path="+a.path:"",a.domain?"; domain="+a.domain:"",a.secure?"; secure":""].join("")}for(var d=r?void 0:{},p=document.cookie?document.cookie.split("; "):[],m=0,x=p.length;x>m;m++){var l=p[m].split("="),g=o(l.shift()),k=l.join("=");if(r&&r===g){d=t(k,c);break}r||void 0===(k=t(k))||(d[g]=k)}return d};u.defaults={},e.removeCookie=function(n,o){return void 0===e.cookie(n)?!1:(e.cookie(n,"",e.extend({},o,{expires:-1})),!e.cookie(n))}});function imgFullScreen(){$('.s_img_fullscreen').click(function(e){var $this=$(this),$bigPhoto=$this.find('.s_img_fullscreen-image'),$mainImg=$this.find('.head_img'),bigPhotoSrc=$mainImg.data('pic4zoom'),$caption=$this.find('.s_img_fullscreen-caption');if(window['g__native_application']&&window['g__send_message_to_host']&&bigPhotoSrc){var captionText=$this.find('.s_img_fullscreen-description').text();var captionSrc=$this.find('.s_img_fullscreen-src').text();g__send_message_to_host('picture',{url:bigPhotoSrc,caption:captionText,src:captionSrc});return;}
    if($this.hasClass('active')){if($(e.target).attr('class')=='s_img_fullscreen-caption-btn'){if($caption.hasClass('m_visible')){$caption.removeClass('m_visible');}else{$caption.addClass('m_visible');}}else{$this.removeClass('active');$caption.removeClass('m_visible');$('body').css('overflow','visible');}}else{if($bigPhoto.attr('src')!=bigPhotoSrc){$bigPhoto.attr('src',bigPhotoSrc);}
        $this.addClass('active');$caption.addClass('m_visible');$('body').css('overflow','hidden');}})}
function elOneHeight(elementArr,maxHeighFlag){var cssProperty=maxHeighFlag?'max-height':'height',elMaxHeight=0,elLength=elementArr.length;for(i=0;i<=elLength;i++){if($(elementArr[i]).outerHeight()>elMaxHeight){elMaxHeight=$(elementArr[i]).outerHeight();}
    if(i==elLength){for(i=0;i<=elLength;i++){$(elementArr[i]).css(cssProperty,elMaxHeight);}}}}
function i_slider($slider){var $slider=$slider,$nav=$slider.find('.i_slider-navigator'),$content=$slider.find('.i_slider-content'),isPhotorep=0,middlePoint=$slider.innerWidth()/2,state=0,touchPoint=null,direction=false,dataItem=$slider.data('start-item')?$slider.data('start-item'):0,threshold=0,windowFlag=0,fullscreenFlag=0,oneImgMaxHeight=false;if($slider.hasClass('b_photoreport')){isPhotorep=1;var $fullscreen=$slider.find('.b_photoreport-fullscreen'),$fullscreenWrap=$fullscreen.find('.wrapper'),fullscreenItemArr=$fullscreenWrap.find('.item'),$fullscreenCurItem=$(fullscreenItemArr[dataItem]),fullscreenWrapPos=$fullscreenWrap.position().left,$bCounter=$slider.find('.b_photoreport-counter'),$bCounterItem=$bCounter.find('.item'),$bCounterLength=$bCounter.find('.length'),$picSrc=$slider.find('.b_photoreport-picsrc'),$fullscreenBtn=$slider.find('.b_photoreport-fullscreenbtn'),$caption=$slider.find('.b_photoreport-caption');$captionWrap=$caption.find('.wrapper'),captionItemArr=$captionWrap.find('.item'),captionItemLength=captionItemArr.length,$capCurItem=$(captionItemArr[dataItem]),captionWrapPos=$captionWrap.position().left,$captionBtn=$caption.find('.b_photoreport-caption-btn');}
    if($nav.length){var $navWrap=$nav.find('.wrapper'),navItemArr=$navWrap.children('.item'),navItemLength=navItemArr.length,navWrapPos=0,noNavbarMovement=$nav.hasClass('m_nomovement')?true:false;for(i=0;i<=navItemLength;i++){$(navItemArr[i]).attr('data-item',i);}
        function activateSlider(){$slider.addClass('activate');navBarMove(dataItem);contentMove(dataItem);};setTimeout(activateSlider,300);}
    if($content.length){var $contentWrap=$content.find('.wrapper'),contentItemArr=$contentWrap.children('.item'),contentItemLength=contentItemArr.length,contentWrapPos=$contentWrap.position().left;for(i=0;i<=contentItemLength;i++){$(contentItemArr[i]).attr('data-item',i);}
        if(isPhotorep==1){var collectImages={};collectImages.initialIndex=0;collectImages.pictures=[];for(i=0;i<fullscreenItemArr.length;i++){let aqUrl=$(fullscreenItemArr[i].children).data('src'),aqCaption=$(fullscreenItemArr[i].children).attr('alt'),aqSrc=$(contentItemArr[i].children).data('imgsrc');collectImages.pictures.push({url:aqUrl,caption:aqCaption,src:aqSrc})}
            $bCounterItem.text('1 ');$bCounterLength.text(contentItemLength);for(i=0;i<=captionItemLength;i++){$(captionItemArr[i]).attr('data-item',i);}
            $fullscreenBtn.click(function(){photorepFullscreen();})
            $captionBtn.click(function(){if($caption.hasClass('m_visible')){$caption.removeClass('m_visible');}else{$caption.addClass('m_visible');}})
            function addImgSrc(dataItem){if($slider.hasClass('m_fullscreen')){for(i=dataItem;i<=(dataItem+3)&&i<contentItemLength;i++){var $image=$(fullscreenItemArr[i].children);if(($image.attr('src')=='')||($image.attr('src')==$image.data('src'))){$image.attr('src',$image.data('src'));}}
                for(i=dataItem;i>=(dataItem-3)&&i>=0;i--){var $image=$(fullscreenItemArr[i].children);if(($image.attr('src')=='')||($image.attr('src')==$image.data('src'))){$image.attr('src',$image.data('src'));}}}
                for(i=dataItem;i<=(dataItem+3)&&i<contentItemLength;i++){var $image=$(contentItemArr[i].children);if($image.attr('src')==''){$image.attr('src',$image.data('src'));}}
                if(!oneImgMaxHeight){var contentImgArr=$contentWrap.find('.item img');elOneHeight(contentImgArr,true);oneImgMaxHeight=true;}
                $picSrc.empty().append($(contentItemArr[dataItem].children).data('imgsrc'));}
            function captionAdd(dataItem){var $curItem=$(captionItemArr[dataItem]),$prevItem=$captionWrap.find('.item.active');$prevItem.removeClass('active');$curItem.addClass('active');if($.trim($curItem.text())==''){$caption.hide();}else{$caption.show();}}}
        function photorepFullscreen(){if(isPhotorep==1){if(window['g__native_application']&&window['g__send_message_to_host']){collectImages.initialIndex=dataItem;g__send_message_to_host('gallery',collectImages);console.log(collectImages);return;}
            if($slider.hasClass('m_fullscreen')){$slider.removeClass('m_fullscreen');$fullscreenBtn.removeClass('active');$caption.removeClass('m_visible');$('body').attr('style','');$('header').css('display','block');fullscreenFlag=0;}else{$slider.addClass('m_fullscreen');$fullscreenBtn.addClass('active');$(fullscreenItemArr[dataItem].children).attr('src',$(fullscreenItemArr[dataItem].children).data('src'));$caption.addClass('m_visible');$('body').css('overflow','hidden');$('header').css('display','none');fullscreenFlag=1;}}}
        if($slider.hasClass('m_medialist')){var $lastSlide=$contentWrap.find('.item.m_lastslide'),lastSlideFlag=1;}
        var $checkEl,zoomFlag;$slider.on('touchstart',function(e){var $checkEl=$(e.target);console.log($checkEl.data('s_fullscreen'));if($checkEl.data('s_fullscreen')){zoomFlag=true;}
            if(!state){state=1;threshold=0;touchPoint=e.changedTouches[0];}});$slider.on('touchmove',function(e){if(state){touch=e.changedTouches[0];threshold=Math.abs(touchPoint.clientX-touch.clientX);thresholdY=Math.abs(touchPoint.clientY-touch.clientY);if((threshold>30)&&(Math.abs(touchPoint.clientX-touch.clientX)>Math.abs(touchPoint.clientY-touch.clientY))){if((touchPoint.clientX-touch.clientX)>0){direction='left';}else if((touchPoint.clientX-touch.clientX)<0){direction='right';}
            if(direction){$contentWrap.css({left:contentWrapPos-(touchPoint.clientX-touch.clientX)});if(fullscreenFlag){$fullscreenWrap.css({left:fullscreenWrapPos-(touchPoint.clientX-touch.clientX)});}}}else if((thresholdY>30)&&(Math.abs(touchPoint.clientX-touch.clientX)<Math.abs(touchPoint.clientY-touch.clientY))){direction='scroll';}else{direction=false;}}});$(document).on('touchend touchcancel',function(e){if(state){if(direction=='left'){dataItem=dataItem+1;}else if(direction=='right'){dataItem=dataItem-1;}
            if(dataItem==contentItemLength){dataItem=contentItemLength-1;}else if(dataItem<0){dataItem=0;}
            if(threshold>30&&direction!='scroll'){if($nav.length){navBarMove(dataItem);}
                if(isPhotorep==1){if($caption.length){captionAdd(dataItem);}
                    addImgSrc(dataItem);$bCounterItem.text((dataItem+1)+' ');}
                contentMove(dataItem);}else if(isPhotorep==1&&direction!='scroll'&&zoomFlag==true){photorepFullscreen();}
            zoomFlag=false;state=0;direction=false;}});$(navItemArr).click(function(){dataItem=$(this).data('item');navBarMove(dataItem);contentMove(dataItem);})
        function orientationChange(){middlePoint=$slider.innerWidth()/2;windowFlag=1;if($nav.length)navBarMove(dataItem);contentMove(dataItem);if(lastSlideFlag){var $firstImg=$content.find('.item-image'),needHeight=$firstImg.height();$lastSlide.css('height',needHeight);}}
        $(window).resize(function(){orientationChange();})
        var mql=window.matchMedia("(orientation: portrait)");mql.addListener(function(m){if(m.matches){orientationChange();}
        else{orientationChange();}});}
    function navBarMove(dataItem){var $navItem=$(navItemArr[dataItem]);if(!noNavbarMovement){navWrapPos=middlePoint-($navItem.position().left+$navItem.outerWidth(true)/2);$navWrap.css('left',navWrapPos);}
        $prevItem=$navWrap.find('.item.active');$prevItem.removeClass('active');$navItem.addClass('active');}
    function contentMove(dataItem){var $contentItem=$(contentItemArr[dataItem]),$fullscreenItem=isPhotorep?$(fullscreenItemArr[dataItem]):'',animateSpeed=windowFlag?0:300,$prevItem=$contentWrap.find('.item.active');$prevItem.removeClass('active');$contentItem.addClass('active');contentWrapPos=(-1)*$contentItem.position().left;$contentWrap.animate({left:contentWrapPos},animateSpeed,function(){contentWrapPos=$contentWrap.position().left;windowFlag=0;});if(fullscreenItemArr){if($(fullscreenItemArr[dataItem].children).attr('src')==''){$(fullscreenItemArr[dataItem].children).attr('src',$(fullscreenItemArr[dataItem].children).data('src'));}
        fullscreenWrapPos=(-1)*$fullscreenItem.position().left;$fullscreenWrap.animate({left:fullscreenWrapPos},animateSpeed,function(){fullscreenWrapPos=$fullscreenWrap.position().left;});}
        if(lastSlideFlag){var $firstImg=$contentItem.find('.item-image'),needHeight=$firstImg.height();$lastSlide.css('height',needHeight);}}}
$(function(){if(typeof(VK)!=='undefined')VK.init({apiId:1992442});var devPixelRatio=function(){if(typeof window=='undefined')return 1;return+window.devicePixelRatio||1;}();var $body=$('body');var $wrapper=$('#wrapper');var $menu_main=$('#menu_main');var $search_form=$('#s_inp_holder');var $search_input=$('#search_input');var $curtain=$('#curtain');var $menu_main_btn=$('#menu_main_btn');var $mtabs=$('.tabs2');var $mtabs_cnt=$mtabs.find('.tabs2_content');var $mtab_n=$mtabs.find('.tab2:eq(0)');var $addmore=$mtab_n.find('.more_news');var copy_content=$('');var msliders=[];var $win=$(window);var orientation=($win.width()>$win.height())?'landscape':'portrait';function menu_main_toggle(){if($curtain.hasClass('active')&&!$menu_main.hasClass('active'))return false;$menu_main_btn.toggleClass('active');$menu_main.toggleClass('active');$curtain.toggleClass('active');if($curtain.hasClass('active')){$(window).on("touchmove.menuscroll",function(event){if($(event.target).parents('#menu_main').length==0){event.preventDefault();}});}
else $(window).off("touchmove.menuscroll");return false;};$menu_main_btn.on('click',menu_main_toggle);$('#to_fullversion').on("click",function(ev){window.location=$(this).attr('href');});$curtain.on("click",menu_main_toggle);function search_submit(evt){if(typeof(evt)!='undefined')evt.preventDefault();var val=$search_input.val();if(val.length==0)return;var query=encodeURIComponent(val);query='?p=search&text='+query+'&how=pt&article=1';window.location.href="/search.shtml"+query;};$('#search_btn').on('click',function(){var $search=$('#search');if($search.hasClass('active')){search_submit();}
else{$search.addClass('active');$search.find('input').focus();}});$('#search_close').on('click',function(){$('#search').removeClass('active');});$search_form.on('submit',search_submit);var $main_article=$('.main_article');if(!$main_article.data('shares-loaded'))soc_count($main_article);$('.news_heads_ajax').on('click','.headline_head',function(){var $this=$(this);var $article=$this.parent();$article.toggleClass('open');if(!$article.data('shares-loaded'))soc_count($article);$this.next().slideToggle(300);});$('#all_rubrics').on('click',function(){$('#menu_rubrics .menu_wrap').slideToggle({duration:400,complete:function(){$('#menu_rubrics').toggleClass('active');}});});$('.foldable .show_more').on('click',function(){var $this=$(this);var $foldable=$this.closest('.foldable');$foldable.toggleClass('fold');var isfold=$foldable.hasClass('fold');if(isfold)$this.text('Развернуть');else $this.text('Cвернуть');return false;});$('#wrapper, #popup').on('click','.social_btn',function(){var $li=$(this);var $article=$('.main_article');if(!$article.length)$article=$li.closest('article');var data_url=$article.data('url');if(typeof(data_url)!='undefined'){var url=data_url;var title=$article.find('h1').text();}
else{var url=window.location.href;var title=$('meta[property="og:title"]').attr('content');};title=$('<div/>').html(title).text();if($li.children().length)var $a=$li.children()
else $a=$li;if($a.hasClass('btn_soc_twi')){window.open($a.attr('href')+'&text='+encodeURIComponent(title),'targetWindow','toolbar=no,location=no,status=no,menubar=no');}
else if($a.hasClass('btn_soc_lj')){window.open($a.attr('href')+'&subject='+encodeURIComponent(title),'targetWindow','toolbar=no,location=no,status=no,menubar=no');}
else if($a.hasClass('btn_popupshow')){var $popup=$('#popup');$popup.find('.popup_content').hide(0);if($a.hasClass('btn_soc_copylink')){$('#permalink_link').text(url);$('#permalink_form').show(0);}
else if($a.hasClass('btn_openshare')){var $pop_soc=$('#popup_socbtn');if(!$pop_soc.hasClass('filled')){$pop_soc.append($('.main_article .social_icons').clone()).addClass('filled');$pop_soc.find('.float_r').remove();};$pop_soc.show(0);};if(!$popup.hasClass('active')){$('#curtain').addClass('active fullcurtain');$('#popup').show(0);$('#popup_close').on('click',function(){$('#curtain').removeClass('active fullcurtain');$('#popup').hide(0);});}}
else{window.open($a.attr('href'),'targetWindow','toolbar=no,location=no,status=no,menubar=no,scrollbars=yes,resizable=yes');};return false;});var $header=$('header');var header_hide_ishidden=false;var header_hide_scrolltop_mem=0;var header_hide_scroll_flag=false;$win.on('scroll',function(){if(header_hide_scroll_flag)return;header_hide_scroll_flag=true;var cur_scrolltop=$win.scrollTop();if(cur_scrolltop>20&&header_hide_scrolltop_mem<cur_scrolltop){if(!header_hide_ishidden&&!$curtain.hasClass('active')){header_hide_ishidden=true;$header.addClass('header_hidden');};}
else if(header_hide_ishidden){header_hide_ishidden=false;$header.removeClass('header_hidden');};header_hide_scrolltop_mem=cur_scrolltop;setTimeout(function(){header_hide_scroll_flag=false;},200);setTimeout(function(){if($(window).scrollTop()<=20){$header.removeClass('header_hidden');}},200);});});$(function(){imgFullScreen();$('.i_slider').each(function(){i_slider($(this));})})